version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.development
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: maple
      MYSQL_DATABASE: chatroom
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hmysql", "-uroot", "-pmaple"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
    